//! Built-in lowercase element constructors for the TUI backend.
//!
//! iodilos keeps a small fixed set of lowercase elements — the terminal UI
//! primitives — and leaves everything else to user-defined uppercase
//! `#[component]` functions (the sycamore convention: lowercase = built-in
//! element, uppercase = component). Each element is a wrapper around a
//! [`TuiNode`] generated by [`impl_element!`] below, forwarding
//! attribute/event/style mutation through [`AsTuiNode`].
//!
//! The built-ins are: `div` (block container / flexbox unit), `span` and `p`
//! (text leaves), `button` and `input` (interactive controls).

use crate::node::{AsTuiNode, TuiNode};
use crate::view::{View, ViewTuiNode};

pub mod completion_menu;
pub mod overlay_box;
pub mod scroll_view;
pub mod table_view;

/// Construct a node for the given static tag string.
fn element(tag: &'static str) -> TuiNode {
    TuiNode::create_element(std::borrow::Cow::Borrowed(tag))
}

/// A custom element created from a hyphenated tag.
pub struct CustomElement(TuiNode);

pub fn custom_element(tag: &'static str) -> CustomElement {
    CustomElement(element(tag))
}

impl From<CustomElement> for View {
    fn from(el: CustomElement) -> Self {
        View::from_node(el.0)
    }
}

impl AsTuiNode for CustomElement {
    fn as_tui_node(&mut self) -> &mut TuiNode {
        &mut self.0
    }
}

/// Defines a built-in lowercase element constructor.
///
/// Each element becomes its own wrapper around a [`TuiNode`], exposed
/// as a `pub fn $name() -> $ty` constructor. The wrappers all forward
/// attribute/event/style mutation through [`AsTuiNode`], so every element
/// shares the identical flat style surface.
macro_rules! impl_element {
    ($name:ident, $ty:ident, $tag:literal) => {
        pub struct $ty($crate::node::TuiNode);

        pub fn $name() -> $ty {
            $ty($crate::components::element($tag))
        }

        impl From<$ty> for $crate::view::View {
            fn from(el: $ty) -> Self {
                $crate::view::View::from_node(el.0)
            }
        }

        impl $crate::node::AsTuiNode for $ty {
            fn as_tui_node(&mut self) -> &mut $crate::node::TuiNode {
                &mut self.0
            }
        }
    };
}

// Built-in lowercase elements — the terminal UI primitives. Each maps to a
// real rendering/layout concern, not an HTML semantic: `div` is the block
// container (flexbox unit), `span`/`p` are inline/paragraph text leaves,
// `button`/`input` are interactive controls. User composition goes through
// uppercase `#[component]` functions instead of inventing more lowercase tags.
impl_element!(div, Div, "div");
impl_element!(span, Span, "span");
impl_element!(p, P, "p");
impl_element!(button, Button, "button");
impl_element!(input, Input, "input");

/// Aggregate re-export of every tag constructor and wrapper type.
pub mod tags {
    pub use super::{Button, button};
    pub use super::{CustomElement, custom_element};
    pub use super::{Div, div};
    pub use super::{Input, input};
    pub use super::{P, p};
    pub use super::{Span, span};
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::attributes::GlobalAttributes;

    #[test]
    fn constructors_build_element_shaped_nodes() {
        let view: View = tags::button().id("save").children("Save").into();
        let node = view
            .nodes()
            .first()
            .expect("button view should contain a node");

        let TuiNode::Element(element) = node else {
            panic!("button constructor should create an element node");
        };
        assert_eq!(element.tag.as_ref(), "button");
        assert_eq!(node.attribute_value("id").as_deref(), Some("save"));
        assert_eq!(element.children.len(), 1);

        let TuiNode::TextSurface { surface, .. } = &element.children[0] else {
            panic!("text child should now be a TextSurface node");
        };
        let surface = surface.borrow();
        assert_eq!(surface.row_count(), 1, "one row for \"Save\"");
        assert_eq!(surface.plain_text(), "Save");
    }
}
