//! HTML tag constructors for the TUI backend.
//!
//! Every HTML tag is a "specialized div": all tags share the same common style
//! attribute surface (layout + border + background + text paint) and differ
//! only by the specialized behavior layered on top. iocraft's generic
//! container `View` is here just `div`.
//!
//! Each tag is a zero-sized wrapper around a [`TuiNode`] generated by the
//! [`impl_element!`] macro below; the wrappers all forward
//! attribute/event/style mutation through [`AsTuiNode`], so every tag shares
//! the identical flat style surface.

use crate::node::{AsTuiNode, TuiNode};
use crate::view::{View, ViewTuiNode};

/// Construct a node for the given static tag string.
fn element(tag: &'static str) -> TuiNode {
    TuiNode::create_element(std::borrow::Cow::Borrowed(tag))
}

/// A custom element created from a hyphenated tag.
pub struct CustomElement(TuiNode);

pub fn custom_element(tag: &'static str) -> CustomElement {
    CustomElement(element(tag))
}

impl From<CustomElement> for View {
    fn from(el: CustomElement) -> Self {
        View::from_node(el.0)
    }
}

impl AsTuiNode for CustomElement {
    fn as_tui_node(&mut self) -> &mut TuiNode {
        &mut self.0
    }
}

/// Defines an HTML tag constructor.
///
/// Each tag becomes its own zero-sized wrapper around a [`TuiNode`], exposed
/// as a `pub fn $name() -> $ty` constructor. The wrappers all forward
/// attribute/event/style mutation through [`AsTuiNode`], so every tag shares
/// the identical flat style surface.
macro_rules! impl_element {
    ($name:ident, $ty:ident, $tag:literal) => {
        pub struct $ty($crate::node::TuiNode);

        pub fn $name() -> $ty {
            $ty($crate::components::element($tag))
        }

        impl From<$ty> for $crate::view::View {
            fn from(el: $ty) -> Self {
                $crate::view::View::from_node(el.0)
            }
        }

        impl $crate::node::AsTuiNode for $ty {
            fn as_tui_node(&mut self) -> &mut $crate::node::TuiNode {
                &mut self.0
            }
        }
    };
}

// Every HTML tag is currently a plain `div`; specialized behavior (e.g. click
// activation for `button`, text editing for `input`) is layered on later by
// replacing the relevant entry below with a hand-written wrapper. `div` is the
// generic block container (iocraft's `View` maps to this).
impl_element!(button, HtmlButton, "button");
impl_element!(div, HtmlDiv, "div");
impl_element!(footer, HtmlFooter, "footer");
impl_element!(header, HtmlHeader, "header");
impl_element!(input, HtmlInput, "input");
impl_element!(li, HtmlLi, "li");
impl_element!(main, HtmlMain, "main");
impl_element!(p, HtmlP, "p");
impl_element!(section, HtmlSection, "section");
impl_element!(span, HtmlSpan, "span");
impl_element!(ul, HtmlUl, "ul");

/// Aggregate re-export of every tag constructor and wrapper type, matching the
/// shape of the old `elements::tags` module so existing imports keep working.
pub mod tags {
    pub use super::{CustomElement, custom_element};
    pub use super::{HtmlButton, button};
    pub use super::{HtmlDiv, div};
    pub use super::{HtmlFooter, footer};
    pub use super::{HtmlHeader, header};
    pub use super::{HtmlInput, input};
    pub use super::{HtmlLi, li};
    pub use super::{HtmlMain, main};
    pub use super::{HtmlP, p};
    pub use super::{HtmlSection, section};
    pub use super::{HtmlSpan, span};
    pub use super::{HtmlUl, ul};
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::attributes::GlobalAttributes;

    #[test]
    fn constructors_build_html_shaped_nodes() {
        let view: View = tags::button().id("save").children("Save").into();
        let node = view
            .nodes()
            .first()
            .expect("button view should contain a node");

        let TuiNode::Element(element) = node else {
            panic!("button constructor should create an element node");
        };
        assert_eq!(element.tag.as_ref(), "button");
        assert_eq!(node.attribute_value("id").as_deref(), Some("save"));
        assert_eq!(element.children.len(), 1);

        let TuiNode::TextStatic { text, .. } = &element.children[0] else {
            panic!("text child should be retained as a text node");
        };
        assert_eq!(text.as_ref(), "Save");
    }
}
